name: duet-ublue
description: Minimal Fedora for Lenovo Duet (MT8183)
base-image: quay.io/fedora/fedora-coreos
image-version: stable

modules:
  # STAGE 1: Install RPMfusion repository configuration packages
  - type: rpm-ostree
    install:
      # These .rpm files configure the RPMfusion repos
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$releasever.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$releasever.noarch.rpm

  # STAGE 2: Now install packages from the configured repos
  - type: rpm-ostree
    install:
      # --- GRAPHICAL BASE (XFCE) ---
      - "@xfce-desktop-environment"
      - xorg-x11-server-Xorg
      - xorg-x11-drv-libinput
      - lightdm
      - lightdm-gtk

      # --- HARDWARE SUPPORT ---
      - kernel-modules-extra
      - mt7601u-firmware
      - linux-firmware
      - libinput
      - xorg-x11-input-libinput
      - xorg-x11-input-evdev
      - xorg-x11-input-synaptics

      # --- UTILS ---
      - network-manager-applet
      - gnome-disk-utility
      - pavucontrol

  - type: systemd
    system:
      enabled:
        - lightdm.service
        - NetworkManager.service
